 github: [metadata]
 encoding: UTF-8
 kramdown:
   input: GFM
   hard_wrap: false
 future: true
 jailed: false

theme: jekyll-theme-hacker
url: "https://actin.github.io"
ls: false

exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
title: Knowledge Box
permalink: pretty

plugins:
  - jekyll-feed

